blank_issues_enabled: true
contact_links:
  - name: Chathouse Homepage
    url: https://chathou.se
  - name: Contact us
    url: https://chathou.se/discord
    about: You can contact us for any other questions or concerns.
